name: Grype Scan

on:
    workflow_dispatch:
        inputs:
            docker_image:
                description: 'Docker image to scan'
                required: true
    workflow_call:
        inputs:
            docker_image:
                required: true
                type: string

jobs:
    grype_scan:
        runs-on: [self-hosted, x86, type-cx42, image-x86-app-docker-ce]
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Docker
          uses: docker/setup-buildx-action@v1

        - name: Run Grype Scan
          run: |
            ./.github/grype/run_grype_scan.sh ${{ github.event.inputs.docker_image || inputs.docker_image }}